version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mighai_user:mighai_pass@db:5432/mighai_db
      - JWT_SECRET=jwt_secret_secure_random_key
      - JWT_REFRESH_SECRET=jwt_refresh_secure_random_key
      - SESSION_SECRET=session_secure_random_key
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mighai_db
      - POSTGRES_USER=mighai_user
      - POSTGRES_PASSWORD=mighai_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: